spring:
  profiles:
    default: local

  output:
    ansi:
      enabled: always

#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
# 기본설정

# 임시설정
  datasource:
    url: jdbc:h2:mem:~/fitlogixApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # (2.5~) Hibernate 초기화 이후 data.sql 실행, 테스트 데이터 넣을 때 넣는 옵션
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true